### ISSUE TITLE
Doesn't work the ChatPane component with IME.

### ISSUE THREAD

**Issue by runceel** [AzureCosmosDB/VectorSearchAiAssistant#48]
In environments where IME is used for languages such as Japanese, Korean, and Chinese, the Enter key is pressed to confirm character conversion. With the current ChatPane component, the chat message is sent at the same time as the character conversion is confirmed, so there is a problem that the chat does not work correctly in environments with IME.

**Comment by runceel** [comment]
To implement this, I guess you have to user JS Interop to handle IME status to handle IME status. Because `compositionstart` event and `compositionend` event are not available for Blazor. Or I guess that you can use `onsubmit` event of `form` instead of `onkeydown`.

I would like to try creating PR for this issue, however I couldn't run it locally. Are there any guide for local debug?

**Comment by joelhulen** [comment]
Closing since this issue was fixed in June.
